// GENERATED by scripts/build-bendle-catalog.mjs — do not edit by hand.
// null until the owner builds the song list: phones then offer only "Use what I typed".
export const BENDLE_CATALOG_URL = null
