import { pureMichiganBackground, PureMichiganForeground } from './pure-michigan-scene.jsx'

export const THEMES = [
  {
    id: 'pure-michigan',
    name: 'Pure Michigan',
    colors: {
      bg:          '#020d12',
      bgDeep:      '#010810',
      accent:      '#1a6b4a',
      highlight:   '#4dffc3',
      text:        '#e8f5f0',
      textMuted:   '#6bbfa0',
      shinyBg:     '#001a12',
      shinyAccent: '#00ffaa',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#4dffc3', count: 0 },  // canvas handles ambient fx
    scene: {
      background: pureMichiganBackground,
      foreground: PureMichiganForeground,
      cssClass:   'theme-pure-michigan',
    },
    transition:    { type: 'aurora-sweep', duration: 160 },
    cutawayFrame:  'birch-bark',  // FrameRegistry falls back to 'none' until built
    roundIntro:    { variant: 'aurora-form', numberColor: '#4dffc3', titleColor: '#e8f5f0', bgColor: '#020d12' },
  },
  {
    id: 'midnight-galaxy',
    name: 'Midnight Galaxy',
    colors: {
      bg:          '#2b1e3e',
      bgDeep:      '#1e1530',
      accent:      '#4a4e8f',
      highlight:   '#a490c2',
      text:        '#e6e6fa',
      textMuted:   '#9988bb',
      shinyBg:     '#3d2060',
      shinyAccent: '#c9a0ff',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#a490c2', count: 40 },
    scene: { background: null, foreground: null, cssClass: 'theme-midnight-galaxy' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#a490c2', titleColor: '#e6e6fa', bgColor: '#2b1e3e' },
  },
  {
    id: 'deep-forest',
    name: 'Deep Forest',
    colors: {
      bg:          '#0d1f0d',
      bgDeep:      '#070e07',
      accent:      '#1a4020',
      highlight:   '#60a000',
      text:        '#d8f0c0',
      textMuted:   '#6a9040',
      shinyBg:     '#0a2010',
      shinyAccent: '#90e030',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#60a000', count: 35 },
    scene: { background: null, foreground: null, cssClass: 'theme-deep-forest' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#60a000', titleColor: '#d8f0c0', bgColor: '#0d1f0d' },
  },
  {
    id: 'harvest-fire',
    name: 'Harvest Fire',
    colors: {
      bg:          '#1e0a02',
      bgDeep:      '#120500',
      accent:      '#7a2808',
      highlight:   '#e04820',
      text:        '#f8e0d0',
      textMuted:   '#c07050',
      shinyBg:     '#2a0e04',
      shinyAccent: '#ff6030',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e04820', count: 45 },
    scene: { background: null, foreground: null, cssClass: 'theme-harvest-fire' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e04820', titleColor: '#f8e0d0', bgColor: '#1e0a02' },
  },
  {
    id: 'cider-season',
    name: 'Cider Season',
    colors: {
      bg:          '#1a1000',
      bgDeep:      '#0e0800',
      accent:      '#4a3000',
      highlight:   '#d4920c',
      text:        '#f8e8c0',
      textMuted:   '#a07030',
      shinyBg:     '#221500',
      shinyAccent: '#f8c040',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#d4920c', count: 30 },
    scene: { background: null, foreground: null, cssClass: 'theme-cider-season' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#d4920c', titleColor: '#f8e8c0', bgColor: '#1a1000' },
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    colors: {
      bg:          '#051520',
      bgDeep:      '#020c14',
      accent:      '#0d4060',
      highlight:   '#20c0b0',
      text:        '#d0f0ee',
      textMuted:   '#408090',
      shinyBg:     '#060e20',
      shinyAccent: '#40e0d0',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#20c0b0', count: 50 },
    scene: { background: null, foreground: null, cssClass: 'theme-northern-lights' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#20c0b0', titleColor: '#d0f0ee', bgColor: '#051520' },
  },
  {
    id: 'harvest-moon',
    name: 'Harvest Moon',
    colors: {
      bg:          '#120810',
      bgDeep:      '#090408',
      accent:      '#4a1530',
      highlight:   '#d46020',
      text:        '#f8d8c0',
      textMuted:   '#906050',
      shinyBg:     '#1a0a14',
      shinyAccent: '#f08040',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#d46020', count: 35 },
    scene: { background: null, foreground: null, cssClass: 'theme-harvest-moon' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#d46020', titleColor: '#f8d8c0', bgColor: '#120810' },
  },
  {
    id: 'midnight-bloom',
    name: 'Midnight Bloom',
    colors: {
      bg:          '#1a0822',
      bgDeep:      '#0e0415',
      accent:      '#5a1060',
      highlight:   '#d050c0',
      text:        '#f0d0f0',
      textMuted:   '#9060a0',
      shinyBg:     '#240b28',
      shinyAccent: '#ff80e0',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#d050c0', count: 40 },
    scene: { background: null, foreground: null, cssClass: 'theme-midnight-bloom' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#d050c0', titleColor: '#f0d0f0', bgColor: '#1a0822' },
  },
  {
    id: 'steel-orchard',
    name: 'Steel Orchard',
    colors: {
      bg:          '#0a1018',
      bgDeep:      '#060810',
      accent:      '#1a3050',
      highlight:   '#5090d0',
      text:        '#d0e8f8',
      textMuted:   '#4070a0',
      shinyBg:     '#0c1520',
      shinyAccent: '#80c0ff',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#5090d0', count: 30 },
    scene: { background: null, foreground: null, cssClass: 'theme-steel-orchard' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#5090d0', titleColor: '#d0e8f8', bgColor: '#0a1018' },
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    colors: {
      bg:          '#18100a',
      bgDeep:      '#0e0804',
      accent:      '#3a2808',
      highlight:   '#c8820c',
      text:        '#f8f0d8',
      textMuted:   '#907040',
      shinyBg:     '#201408',
      shinyAccent: '#f8b040',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#c8820c', count: 25 },
    scene: { background: null, foreground: null, cssClass: 'theme-golden-hour' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#c8820c', titleColor: '#f8f0d8', bgColor: '#18100a' },
  },
  {
    id: 'blood-orange',
    name: 'Blood Orange',
    colors: {
      bg:          '#1a0800',
      bgDeep:      '#0e0400',
      accent:      '#501800',
      highlight:   '#e04010',
      text:        '#f8d0c0',
      textMuted:   '#a06040',
      shinyBg:     '#220a00',
      shinyAccent: '#ff6020',
    },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e04010', count: 45 },
    scene: { background: null, foreground: null, cssClass: 'theme-blood-orange' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e04010', titleColor: '#f8d0c0', bgColor: '#1a0800' },
  },
]

export const DEFAULT_THEME_ID = 'midnight-galaxy'

export function getTheme(id) {
  return THEMES.find(t => t.id === id) ?? THEMES[0]
}
