export const THEMES = [
  {
    id: 'pure-michigan',
    name: 'Pure Michigan',
    colors: { bg: '#020d12', bgDeep: '#010810', accent: '#1a6b4a', highlight: '#4dffc3', text: '#e8f5f0', textMuted: '#6bbfa0', shinyBg: '#001a12', shinyAccent: '#00ffaa' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#4dffc3', count: 30, behavior: 'twinkle' },
    vignette: { r: 0, g: 2, b: 5, strength: 0.52 },
    scene: { background: null, foreground: null, cssClass: 'theme-pure-michigan' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#4dffc3', titleColor: '#e8f5f0', bgColor: '#020d12' },
  },
  {
    id: 'midnight-galaxy',
    name: 'Midnight Galaxy',
    colors: { bg: '#08001a', bgDeep: '#040010', accent: '#4a1a8f', highlight: '#c060ff', text: '#e8d0ff', textMuted: '#8050b0', shinyBg: '#120030', shinyAccent: '#ff40a0' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#c060ff', count: 50, behavior: 'twinkle' },
    vignette: { r: 0, g: 0, b: 3, strength: 0.60 },
    scene: { background: null, foreground: null, cssClass: 'theme-midnight-galaxy' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#c060ff', titleColor: '#e8d0ff', bgColor: '#08001a' },
  },
  {
    id: 'autumn-harvest',
    name: 'Autumn Harvest',
    colors: { bg: '#1a0800', bgDeep: '#0e0400', accent: '#7a2808', highlight: '#ff6820', text: '#f8d8b0', textMuted: '#a05030', shinyBg: '#220a00', shinyAccent: '#e8a020' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#ff6820', count: 35, behavior: 'ash' },
    vignette: { r: 8, g: 2, b: 0, strength: 0.55 },
    scene: { background: null, foreground: null, cssClass: 'theme-autumn-harvest' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff6820', titleColor: '#f8d8b0', bgColor: '#1a0800' },
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    colors: { bg: '#020c18', bgDeep: '#010810', accent: '#0d5040', highlight: '#40ffcc', text: '#c0f0e8', textMuted: '#408070', shinyBg: '#001020', shinyAccent: '#80ff80' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#40ffcc', count: 30, behavior: 'float' },
    vignette: { r: 0, g: 2, b: 8, strength: 0.58 },
    scene: { background: null, foreground: null, cssClass: 'theme-northern-lights' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#40ffcc', titleColor: '#c0f0e8', bgColor: '#020c18' },
  },
  {
    id: 'medieval-tavern',
    name: 'Medieval Tavern',
    colors: { bg: '#0e0800', bgDeep: '#080400', accent: '#5a2a08', highlight: '#e08020', text: '#f0d8a0', textMuted: '#907040', shinyBg: '#180c00', shinyAccent: '#ffb040' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e08020', count: 20, behavior: 'smoke' },
    vignette: { r: 3, g: 1, b: 0, strength: 0.60 },
    scene: { background: null, foreground: null, cssClass: 'theme-medieval-tavern' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e08020', titleColor: '#f0d8a0', bgColor: '#0e0800' },
  },
  {
    id: 'sunset-boulevard',
    name: 'Sunset Boulevard',
    colors: { bg: '#100818', bgDeep: '#080410', accent: '#801840', highlight: '#ff4080', text: '#f8e0f0', textMuted: '#905060', shinyBg: '#180820', shinyAccent: '#40d0ff' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#ff4080', count: 25, behavior: 'float' },
    vignette: { r: 10, g: 2, b: 0, strength: 0.50 },
    scene: { background: null, foreground: null, cssClass: 'theme-sunset-boulevard' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff4080', titleColor: '#f8e0f0', bgColor: '#100818' },
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    colors: { bg: '#040010', bgDeep: '#020008', accent: '#3a0880', highlight: '#a020ff', text: '#e0c0ff', textMuted: '#604080', shinyBg: '#080018', shinyAccent: '#20ff80' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#a020ff', count: 60, behavior: 'pixel' },
    vignette: { r: 2, g: 0, b: 5, strength: 0.58 },
    scene: { background: null, foreground: null, cssClass: 'theme-retro-arcade' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#a020ff', titleColor: '#e0c0ff', bgColor: '#040010' },
  },
  {
    id: 'sand-dune-chill',
    name: 'Sand Dune Chill',
    colors: { bg: '#100d05', bgDeep: '#0c0a03', accent: '#3a2808', highlight: '#e8c060', text: '#f0e8c8', textMuted: '#907040', shinyBg: '#181205', shinyAccent: '#60b8e0' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e8c060', count: 20, behavior: 'float' },
    vignette: { r: 5, g: 3, b: 0, strength: 0.50 },
    scene: { background: null, foreground: null, cssClass: 'theme-sand-dune-chill' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e8c060', titleColor: '#f0e8c8', bgColor: '#100d05' },
  },
  {
    id: 'halloween',
    name: 'Halloween',
    colors: { bg: '#060008', bgDeep: '#030005', accent: '#380858', highlight: '#a000ff', text: '#e0c0f8', textMuted: '#604080', shinyBg: '#0a0010', shinyAccent: '#ff6800' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#a000ff', count: 30, behavior: 'ash' },
    vignette: { r: 3, g: 0, b: 5, strength: 0.65 },
    scene: { background: null, foreground: null, cssClass: 'theme-halloween' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#a000ff', titleColor: '#e0c0f8', bgColor: '#060008' },
  },
  {
    id: 'jazz-club',
    name: 'Jazz Club',
    colors: { bg: '#080608', bgDeep: '#040404', accent: '#4a2808', highlight: '#d4820c', text: '#f0d890', textMuted: '#806040', shinyBg: '#100800', shinyAccent: '#40a8d0' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#d4820c', count: 15, behavior: 'smoke' },
    vignette: { r: 4, g: 2, b: 0, strength: 0.58 },
    scene: { background: null, foreground: null, cssClass: 'theme-jazz-club' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#d4820c', titleColor: '#f0d890', bgColor: '#080608' },
  },
  {
    id: 'dive-bar',
    name: 'Dive Bar',
    colors: { bg: '#100008', bgDeep: '#080005', accent: '#600818', highlight: '#ff2040', text: '#f8d0d8', textMuted: '#903040', shinyBg: '#180008', shinyAccent: '#ff8000' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#ff2040', count: 30, behavior: 'float' },
    vignette: { r: 5, g: 0, b: 1, strength: 0.60 },
    scene: { background: null, foreground: null, cssClass: 'theme-dive-bar' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff2040', titleColor: '#f8d0d8', bgColor: '#100008' },
  },
  {
    id: 'rooftop-party',
    name: 'Rooftop Party',
    colors: { bg: '#040818', bgDeep: '#020410', accent: '#0a1840', highlight: '#4080ff', text: '#d0e0ff', textMuted: '#304080', shinyBg: '#080c20', shinyAccent: '#80ffff' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#4080ff', count: 45, behavior: 'confetti' },
    vignette: { r: 0, g: 1, b: 5, strength: 0.52 },
    scene: { background: null, foreground: null, cssClass: 'theme-rooftop-party' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#4080ff', titleColor: '#d0e0ff', bgColor: '#040818' },
  },
  {
    id: 'christmas-eve',
    name: 'Christmas Eve',
    colors: { bg: '#030204', bgDeep: '#020103', accent: '#3a0810', highlight: '#ff4040', text: '#f8f0f0', textMuted: '#806060', shinyBg: '#080408', shinyAccent: '#40d840' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#f0f4ff', count: 60, behavior: 'snow' },
    vignette: { r: 8, g: 0, b: 2, strength: 0.55 },
    scene: { background: null, foreground: null, cssClass: 'theme-christmas-eve' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff4040', titleColor: '#f8f0f0', bgColor: '#030204' },
  },
  {
    id: 'drive-in-movie',
    name: 'Drive-In Movie',
    colors: { bg: '#080410', bgDeep: '#040208', accent: '#280848', highlight: '#e0a000', text: '#f8f0d0', textMuted: '#806040', shinyBg: '#100818', shinyAccent: '#ff6820' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e0a000', count: 20, behavior: 'float' },
    vignette: { r: 2, g: 0, b: 4, strength: 0.55 },
    scene: { background: null, foreground: null, cssClass: 'theme-drive-in-movie' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e0a000', titleColor: '#f8f0d0', bgColor: '#080410' },
  },
  {
    id: 'western-showdown',
    name: 'Western Showdown',
    colors: { bg: '#100800', bgDeep: '#080400', accent: '#602000', highlight: '#e06010', text: '#f8e0b0', textMuted: '#905030', shinyBg: '#180a00', shinyAccent: '#ffd040' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e06010', count: 25, behavior: 'ash' },
    vignette: { r: 8, g: 2, b: 0, strength: 0.55 },
    scene: { background: null, foreground: null, cssClass: 'theme-western-showdown' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e06010', titleColor: '#f8e0b0', bgColor: '#100800' },
  },
  {
    id: 'under-the-sea',
    name: 'Under the Sea',
    colors: { bg: '#000c18', bgDeep: '#000810', accent: '#003848', highlight: '#00d8c0', text: '#b0f0f0', textMuted: '#207870', shinyBg: '#001020', shinyAccent: '#40ffb0' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#00d8c0', count: 35, behavior: 'float' },
    vignette: { r: 0, g: 1, b: 6, strength: 0.70 },
    scene: { background: null, foreground: null, cssClass: 'theme-under-the-sea' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#00d8c0', titleColor: '#b0f0f0', bgColor: '#000c18' },
  },
  {
    id: 'neon-tokyo',
    name: 'Neon Tokyo',
    colors: { bg: '#040008', bgDeep: '#020005', accent: '#380048', highlight: '#ff00c0', text: '#f8d0ff', textMuted: '#803080', shinyBg: '#080010', shinyAccent: '#00ffff' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#ff00c0', count: 55, behavior: 'pixel' },
    vignette: { r: 0, g: 0, b: 2, strength: 0.65 },
    scene: { background: null, foreground: null, cssClass: 'theme-neon-tokyo' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff00c0', titleColor: '#f8d0ff', bgColor: '#040008' },
  },
  {
    id: 'firefly-summer',
    name: 'Firefly Summer',
    colors: { bg: '#040e04', bgDeep: '#020a02', accent: '#1a3808', highlight: '#d4a020', text: '#e8f0c0', textMuted: '#607040', shinyBg: '#081000', shinyAccent: '#a0ff40' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#d4a020', count: 20, behavior: 'firefly' },
    vignette: { r: 0, g: 3, b: 0, strength: 0.55 },
    scene: { background: null, foreground: null, cssClass: 'theme-firefly-summer' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#d4a020', titleColor: '#e8f0c0', bgColor: '#040e04' },
  },
  {
    id: 'wine-cellar',
    name: 'Wine Cellar',
    colors: { bg: '#0c0006', bgDeep: '#080004', accent: '#480018', highlight: '#c02040', text: '#f0d0d8', textMuted: '#804050', shinyBg: '#120008', shinyAccent: '#e8a0b0' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#c02040', count: 15, behavior: 'smoke' },
    vignette: { r: 3, g: 0, b: 1, strength: 0.65 },
    scene: { background: null, foreground: null, cssClass: 'theme-wine-cellar' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#c02040', titleColor: '#f0d0d8', bgColor: '#0c0006' },
  },
  {
    id: 'meteor-shower',
    name: 'Meteor Shower',
    colors: { bg: '#020408', bgDeep: '#010306', accent: '#101828', highlight: '#e0f0ff', text: '#f0f8ff', textMuted: '#406080', shinyBg: '#040810', shinyAccent: '#80c0ff' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#e0f0ff', count: 70, behavior: 'twinkle' },
    vignette: { r: 0, g: 0, b: 2, strength: 0.62 },
    scene: { background: null, foreground: null, cssClass: 'theme-meteor-shower' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#e0f0ff', titleColor: '#f0f8ff', bgColor: '#020408' },
  },
  {
    id: 'eighties-night',
    name: '80s Night',
    colors: { bg: '#080010', bgDeep: '#040008', accent: '#300858', highlight: '#ff1090', text: '#f8d0ff', textMuted: '#804070', shinyBg: '#100018', shinyAccent: '#00d0ff' },
    fonts: { display: 'Boogaloo', body: 'DM Sans', ui: 'DM Sans' },
    particles: { color: '#ff1090', count: 55, behavior: 'confetti' },
    vignette: { r: 2, g: 0, b: 5, strength: 0.60 },
    scene: { background: null, foreground: null, cssClass: 'theme-eighties-night' },
    transition: { type: 'default', duration: 160 },
    cutawayFrame: 'none',
    roundIntro: { variant: 'default', numberColor: '#ff1090', titleColor: '#f8d0ff', bgColor: '#080010' },
  },
]

export const DEFAULT_THEME_ID = 'pure-michigan'

export function getTheme(id) {
  return THEMES.find(t => t.id === id) ?? THEMES[0]
}
