// concepts/tools/sanitize-svg.mjs
//
// Parser-based SVG sanitizer for the Round-Journey Designer Agent (see PLAN.md §3d, §3f).
// Every sprite SVG generated by Recraft (or drawn as a fallback primitive) MUST pass this
// before being embedded inline in a prototype. Fails closed: any error, any disallowed
// construct, any limit breach -> { ok: false }. Never regex-only — uses a real XML parser
// (@xmldom/xmldom) so structural attacks (nested entities, malformed trees) can't slip past
// a naive string match.
//
// Defends against, in order:
//   1. Oversized input (memory/DoS)
//   2. DOCTYPE / ENTITY declarations (billion-laughs / entity-expansion DoS)
//   3. Malformed XML (parse errors)
//   4. Non-SVG root
//   5. Disallowed elements (script, foreignObject, image, style, animate*, iframe, ...)
//   6. Disallowed attributes (event handlers, non-local href/url() references)
//   7. Excessive node count / tree depth (DOM-bomb DoS)
//
// On success, returns the sanitized SVG re-serialized from the pruned DOM (never the
// original string) — so nothing that survives is unaccounted for by this file's own logic.

import { DOMParser, XMLSerializer } from '@xmldom/xmldom';

export const DEFAULT_LIMITS = {
  maxBytes: 300_000,   // a flat-icon sprite should be a few KB; 300KB is generous headroom
  maxDepth: 40,
  maxNodes: 3000,
};

// Elements allowed to survive sanitization. Deliberately excludes: script, style,
// foreignObject, image, iframe, animate/animateTransform/animateMotion/set (motion is
// owned by the prototype's own GSAP/rAF code, never baked into the sprite), a, use
// (both are common SSRF/reference-leak vectors and add no value for a static icon sprite).
const ALLOWED_ELEMENTS = new Set([
  'svg', 'g', 'defs', 'title', 'desc',
  'path', 'rect', 'circle', 'ellipse', 'line', 'polyline', 'polygon',
  'lineargradient', 'radialgradient', 'stop', 'clippath', 'mask',
]);

// Attributes allowed per element (lowercased). '*' entries apply to every allowed element.
const GLOBAL_ATTRS = new Set(['id', 'class', 'transform', 'opacity', 'clip-path', 'mask']);
const ALLOWED_ATTRS = {
  svg: new Set(['xmlns', 'viewbox', 'width', 'height', 'preserveaspectratio', 'version']),
  path: new Set(['d', 'fill', 'stroke', 'stroke-width', 'stroke-linecap', 'stroke-linejoin', 'fill-opacity', 'stroke-opacity', 'fill-rule']),
  rect: new Set(['x', 'y', 'width', 'height', 'rx', 'ry', 'fill', 'stroke', 'stroke-width', 'fill-opacity', 'stroke-opacity']),
  circle: new Set(['cx', 'cy', 'r', 'fill', 'stroke', 'stroke-width', 'fill-opacity', 'stroke-opacity']),
  ellipse: new Set(['cx', 'cy', 'rx', 'ry', 'fill', 'stroke', 'stroke-width', 'fill-opacity', 'stroke-opacity']),
  line: new Set(['x1', 'y1', 'x2', 'y2', 'stroke', 'stroke-width', 'stroke-linecap']),
  polyline: new Set(['points', 'fill', 'stroke', 'stroke-width', 'fill-opacity', 'stroke-opacity']),
  polygon: new Set(['points', 'fill', 'stroke', 'stroke-width', 'fill-opacity', 'stroke-opacity']),
  lineargradient: new Set(['x1', 'y1', 'x2', 'y2', 'gradientunits', 'gradienttransform']),
  radialgradient: new Set(['cx', 'cy', 'r', 'fx', 'fy', 'gradientunits', 'gradienttransform']),
  stop: new Set(['offset', 'stop-color', 'stop-opacity']),
  g: new Set(['fill', 'stroke']),
  clippath: new Set(['clippathunits']),
  mask: new Set(['maskunits']),
  defs: new Set([]),
  title: new Set([]),
  desc: new Set([]),
};

// Attribute VALUES get their own check regardless of the name allowlist above — this is
// what stops url(https://evil) / href="https://evil" from riding in on an otherwise
// legitimate attribute name.
function isSafeAttrValue(name, value) {
  const v = String(value).trim();
  const lower = v.toLowerCase();
  if (lower.startsWith('javascript:')) return false;
  if (lower.includes('data:text/html')) return false;
  // fill="url(#localGradient)" is fine; fill="url(https://...)" is not. Check EVERY
  // url(...) occurrence, not just the first — `matchAll` (not `match`), so a value like
  // "url(#safe) url(https://evil)" can't hide a second, unsafe reference behind a first
  // safe-looking one.
  const urlMatches = [...v.matchAll(/url\(\s*['"]?([^'")]+)['"]?\s*\)/gi)];
  for (const m of urlMatches) {
    if (!m[1].startsWith('#')) return false;
  }
  if ((name === 'href' || name === 'xlink:href') && !v.startsWith('#')) return false;
  return true;
}

function countBytes(str) {
  return Buffer.byteLength(str, 'utf8');
}

function walkAndSanitize(node, depth, counters, limits) {
  if (depth > limits.maxDepth) throw new Error(`max depth ${limits.maxDepth} exceeded`);

  // ELEMENT_NODE = 1
  if (node.nodeType === 1) {
    counters.nodes += 1;
    if (counters.nodes > limits.maxNodes) throw new Error(`max node count ${limits.maxNodes} exceeded`);

    const tag = node.tagName.toLowerCase();
    if (!ALLOWED_ELEMENTS.has(tag)) {
      throw new Error(`disallowed element <${node.tagName}>`);
    }

    const allowedForTag = ALLOWED_ATTRS[tag] || new Set();
    const attrsToRemove = [];
    for (let i = 0; i < node.attributes.length; i++) {
      const attr = node.attributes[i];
      const attrName = attr.name.toLowerCase();

      if (attrName.startsWith('on')) {
        throw new Error(`event-handler attribute "${attr.name}" on <${node.tagName}>`);
      }
      // href/xlink:href get a dedicated check regardless of whether they're in that
      // element's attribute allowlist. An unsafe (non-local) value is a HARD REJECT of the
      // whole document, not a silent strip — a stripped attribute is functionally safe
      // (nothing external survives) but invisible to the audit log; a rejected file shows
      // up in NIGHTLY-LOG.md as "this sprite tried to reference something external and was
      // thrown out," which is the fail-closed behavior PLAN.md actually calls for. None of
      // the allowed elements here need href for a static icon sprite, so a *safe* local
      // href is still dropped below — this branch only exists to catch the unsafe case
      // before it can be silently swallowed by the generic allowlist-strip path.
      if (attrName === 'href' || attrName === 'xlink:href') {
        if (!isSafeAttrValue(attrName, attr.value)) {
          throw new Error(`unsafe href value on <${node.tagName}>: ${attr.value}`);
        }
        attrsToRemove.push(attr.name);
        continue;
      }
      const isAllowedName = GLOBAL_ATTRS.has(attrName) || allowedForTag.has(attrName) || attrName === 'xmlns';
      if (!isAllowedName) {
        attrsToRemove.push(attr.name);
        continue;
      }
      if (!isSafeAttrValue(attrName, attr.value)) {
        throw new Error(`unsafe value on attribute "${attr.name}" (<${node.tagName}>): ${attr.value}`);
      }
    }
    for (const name of attrsToRemove) node.removeAttribute(name);

    for (let i = 0; i < node.childNodes.length; i++) {
      walkAndSanitize(node.childNodes[i], depth + 1, counters, limits);
    }
  }
  // Text/comment/CDATA nodes are left as-is (comments are harmless and stripped by the
  // serializer's normal behavior in practice; explicit comment-stripping is not required
  // for the threat model here, since nothing executes from a comment).
}

/**
 * @param {string} svgString  Raw SVG text (e.g. straight from a Recraft generation).
 * @param {object} [limits]   Override DEFAULT_LIMITS.
 * @returns {{ ok: true, svg: string } | { ok: false, reason: string }}
 */
export function sanitizeSVG(svgString, limits = {}) {
  const opts = { ...DEFAULT_LIMITS, ...limits };

  if (typeof svgString !== 'string' || svgString.length === 0) {
    return { ok: false, reason: 'empty or non-string input' };
  }

  if (countBytes(svgString) > opts.maxBytes) {
    return { ok: false, reason: `input exceeds max byte size (${opts.maxBytes})` };
  }

  // Reject any DOCTYPE/ENTITY declaration outright before parsing at all — this is the
  // billion-laughs / entity-expansion guard. A legitimate icon sprite never needs a
  // DOCTYPE, so there is no false-positive cost to banning it unconditionally.
  if (/<!DOCTYPE/i.test(svgString) || /<!ENTITY/i.test(svgString)) {
    return { ok: false, reason: 'DOCTYPE/ENTITY declarations are not permitted' };
  }

  let doc;
  const parseErrors = [];
  try {
    // @xmldom/xmldom's error-reporting API is `onError(level, msg)`, not the older
    // errorHandler-object shape (that older shape throws "no longer supported" and masks
    // every real parse result behind a false rejection — caught by the fixture test suite,
    // not by reading the docs, which is exactly why that suite exists). Only 'error' and
    // 'fatalError' levels are treated as rejections; 'warning' is not fatal.
    const parser = new DOMParser({
      onError: (level, msg) => {
        if (level === 'error' || level === 'fatalError') parseErrors.push(String(msg));
      },
    });
    doc = parser.parseFromString(svgString, 'image/svg+xml');
  } catch (err) {
    return { ok: false, reason: `XML parse threw: ${err.message}` };
  }
  if (parseErrors.length > 0) {
    return { ok: false, reason: `XML parse error: ${parseErrors[0]}` };
  }
  if (!doc || !doc.documentElement) {
    return { ok: false, reason: 'XML parse produced no document element' };
  }

  const root = doc.documentElement;
  if (!root || root.tagName.toLowerCase() !== 'svg') {
    return { ok: false, reason: 'root element is not <svg>' };
  }

  // Reject anything outside the root element — a processing instruction (e.g.
  // <?xml-stylesheet href="https://evil...">), a second top-level element, or any other
  // sibling of the root — rather than silently dropping it. Silently dropping would
  // technically be safe (only `root` ever gets serialized, see below), but this
  // sanitizer's whole design is fail-closed and auditable: an SVG that arrives with
  // unexpected top-level content is suspicious enough to reject outright, on the record,
  // not swallow quietly. Whitespace-only text nodes and comments are harmless and allowed.
  for (let i = 0; i < doc.childNodes.length; i++) {
    const n = doc.childNodes[i];
    if (n === root) continue;
    const isHarmlessText = n.nodeType === 3 && !/\S/.test(n.nodeValue || ''); // TEXT_NODE, whitespace-only
    const isComment = n.nodeType === 8; // COMMENT_NODE
    if (!isHarmlessText && !isComment) {
      return { ok: false, reason: `unexpected top-level node outside <svg> root (nodeType ${n.nodeType})` };
    }
  }

  // The root must genuinely be in the SVG namespace — a same-named-but-wrong-namespace
  // element (or no namespace at all) is not what this sanitizer is designed to reason
  // about and must not be waved through just because its tag text reads "svg".
  if (root.namespaceURI !== 'http://www.w3.org/2000/svg') {
    return { ok: false, reason: `root element is not in the SVG namespace (got: ${root.namespaceURI})` };
  }

  try {
    const counters = { nodes: 0 };
    walkAndSanitize(root, 0, counters, opts);
  } catch (err) {
    return { ok: false, reason: err.message };
  }

  // Serialize ONLY the sanitized root — never the whole `doc`. Serializing `doc` would
  // re-emit anything sitting outside root even after this function decided root was safe
  // (the top-level-node check above rejects the whole file if such content exists, but
  // that check existing is exactly why serializing only `root` here isn't redundant: it's
  // the second, independent layer — belt and suspenders — matching this file's own
  // fail-closed philosophy rather than relying on a single check).
  const cleaned = new XMLSerializer().serializeToString(root);
  return { ok: true, svg: cleaned };
}
