// scripts/build-us-map.mjs
// One-time generator. Run: node scripts/build-us-map.mjs
// Projects US Census state outlines (us-atlas, public domain) with the SAME
// project() the runtime inverts, fits them to a 1000-wide frame, and writes
// usMapFrame.js (tiny, eager) + usMapData.js (paths, lazy-loaded).
import { readFileSync, writeFileSync } from 'node:fs'
import { feature } from 'topojson-client'
import { project } from '../client/src/lib/usProjection.js'

const topo = JSON.parse(readFileSync(new URL('../node_modules/us-atlas/states-10m.json', import.meta.url), 'utf8'))
const NON_LOWER_48 = new Set(['02', '15', '60', '66', '69', '72', '78']) // AK, HI, territories
const states = feature(topo, topo.objects.states).features.filter(f => !NON_LOWER_48.has(String(f.id).padStart(2, '0')))
if (states.length !== 49) throw new Error(`expected 49 (48 states + DC), got ${states.length}`)

// project, flip y for SVG
const proj = ([lon, lat]) => { const [x, y] = project(lon, lat); return [x, -y] }
const polys = f => (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates)

let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
for (const f of states) for (const poly of polys(f)) for (const ring of poly) for (const c of ring) {
  const [x, y] = proj(c)
  if (x < minX) minX = x; if (x > maxX) maxX = x
  if (y < minY) minY = y; if (y > maxY) maxY = y
}
const WIDTH = 1000
const scale = WIDTH / (maxX - minX)
const tx = -minX * scale
const ty = -minY * scale
const height = Math.round((maxY - minY) * scale)
const r1 = n => Math.round(n * 10) / 10

const out = states.map(f => {
  const d = polys(f).map(poly => poly.map(ring =>
    'M' + ring.map(c => { const [x, y] = proj(c); return `${r1(x * scale + tx)} ${r1(y * scale + ty)}` }).join('L') + 'Z'
  ).join('')).join('')
  return { id: String(f.id).padStart(2, '0'), name: f.properties.name, d }
})

writeFileSync(new URL('../client/src/lib/usMapFrame.js', import.meta.url),
  `// GENERATED by scripts/build-us-map.mjs — do not edit.\nexport const US_MAP_FRAME = ${JSON.stringify({ scale, tx, ty, width: WIDTH, height })}\n`)
writeFileSync(new URL('../client/src/lib/usMapData.js', import.meta.url),
  `// GENERATED by scripts/build-us-map.mjs — do not edit. Lazy-load via useUsMapData().\nexport const US_STATES = ${JSON.stringify(out)}\n`)
console.log(`wrote ${out.length} states, frame ${WIDTH}x${height}`)
